version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - dish-service
      - cart-service
      - order-service

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - PORT=4001
    expose:
      - "4001"

  dish-service:
    build: ./dish-service
    container_name: dish-service
    environment:
      - PORT=4002
    expose:
      - "4002"

  cart-service:
    build: ./cart-service
    container_name: cart-service
    environment:
      - PORT=4003
    expose:
      - "4003"

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      - PORT=4004
    expose:
      - "4004"
